apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kblfz70aq-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e621fe3676.rg4c.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:8eab9627a63530f0d02dcfb77c81b0ce88ce8c74@sha256:daed1265aa3b84eef03630f7d741a280570040260c2f24fea552147efff2d0ef
          name: container-image
