apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kblfz70aq-nodejs
  janus-idp.io/tekton: kblfz70aq-nodejs
  backstage.io/kubernetes-id: kblfz70aq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kblfz70aq-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
